services:
  - type: web
    name: writegen-backend
    env: docker
    plan: starter
    repo: https://github.com/abhilash-abhi178/WriteGen-backend-firebase
    branch: main
    healthCheckPath: /
    dockerfilePath: Dockerfile
    startCommand: uvicorn server:app --host 0.0.0.0 --port 10000
    envVars:
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false